import os
import numpy as np
import src.config as c

from stable_baselines3 import PPO, DQN, A2C
from sb3_contrib import ARS, QRDQN, TRPO

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

TOTAL_TIMESTEPS = [100_000, 500_000, 1_000_000]
if c.TRAIN_ON_ALL_SETS and c.LARGE_PRODUCT_SET:
    TOTAL_TIMESTEPS.append(2_000_000)

N_EVAL_EPISODES = 15
N_ESTIMATION_EPISODES = 50

T = 410
C = 185
n = 100 if c.LARGE_PRODUCT_SET else 10
ARRIVAL_PROB = 0.5
r = np.linspace(600, 175, n) if c.LARGE_PRODUCT_SET else np.asarray([600, 550, 475, 400, 300, 280, 240, 200, 185, 175], dtype=float)

LEARNING_CURVE_ENABLED = False
PROGRESS_BAR_ENABLED = True

DEMAND_MODELS = (
    "MNL",
    "MMNL_2PT",
    "MMNL_5PT",
	"Probit",
    "MProbit",
	"MNLrefPrice",
	"MNLConsidSet",
    "TMNL",
	"NLogit"
)

# Demand-model parameters
MMNL_2PT_BETA_MULTIPLIERS = np.asarray([0.5, 1.5], dtype=float)
MMNL_5PT_BETA_MULTIPLIERS = np.asarray([0.6, 0.8, 1.0, 1.2, 1.4], dtype=float)

MNL_REFERENCE_PRICE_BETA_GAIN = 0.0025
MNL_REFERENCE_PRICE_BETA_LOSS = 0.0035

MNL_CONSIDERATION_LOGIT_SLOPE = 0.0125
MNL_CONSIDERATION_EXACT_MAX_PRODUCTS = 20
MNL_CONSIDERATION_QUADRATURE_POINTS = 64
MNL_CONSIDERATION_NORMALIZATION_TOLERANCE = 1e-10
MNL_CONSIDERATION_SUBSET_CACHE_SIZE = 32
MNL_CONSIDERATION_QUADRATURE_CACHE_SIZE = 8

NESTED_LOGIT_MU_A = 0.7
NESTED_LOGIT_MU_B = 0.8

TMNL_DEFAULT_DELTA = 0.5
TMNL_OUTSIDE_UTILITY = -1.0

PROBIT_DEFAULT_BLOCKS = 2
PROBIT_DEFAULT_RHO_WITHIN = 0.35
PROBIT_DEFAULT_RHO_BETWEEN = 0.10
PROBIT_DEFAULT_RHO_OUTSIDE = 0.05
PROBIT_EIGENVALUE_FLOOR = 1e-8
PROBIT_STD_FLOOR = 1e-12
PROBIT_CHOLESKY_CACHE_SIZE = 4

# Gurobi solver constants
MAX_STATE_SOLVE_SECONDS = 1.0
MAX_EFFICIENT_SET_SOLVE_SECONDS = 60.0

# Efficient-frontier search constants
EFFICIENT_SET_FRONTIER_Q_EPS = 1e-8
EFFICIENT_SET_NUMERIC_TOL = 1e-10
EFFICIENT_SET_BRUTE_TOL = 1e-12
EFFICIENT_SET_BRUTE_CACHE_SIZE = 8

# Estimation constants
ESTIMATION_BETA_BOUNDS = (-0.05, -1e-7)
SCIPY_ESTIMATION_METHOD = "L-BFGS-B"
SCIPY_ESTIMATION_MAXITER_DEFAULT = 500
SCIPY_ESTIMATION_SEED_DEFAULT = 42
SCIPY_MNL_RESTARTS_DEFAULT = 3
SCIPY_MMNL_RESTARTS_DEFAULT = 7
SCIPY_MMNL2_MIN_WEIGHT_DEFAULT = 0.2
SCIPY_MMNL5_MIN_WEIGHT_DEFAULT = 0.1
SCIPY_MMNL_MIN_WEIGHT_FLOOR_DEFAULT = 1e-8
SCIPY_NEG_LOG_LIKELIHOOD_FLOOR = 1e-300
SCIPY_INFEASIBLE_OBJECTIVE_VALUE = 1e100
SCIPY_BETA_JITTER_SCALE_FRACTION = 0.1
SCIPY_BETA_EDGE_TOL = 1e-6
SCIPY_BETA_FALLBACK_LOWER_BOUND = -0.01
SCIPY_BETA_FALLBACK_MIN_PURCHASE_RATE = 0.5
SCIPY_BETA_FALLBACK_THRESHOLD = -0.01
SCIPY_FALLBACK_OBJECTIVE_TOL = 1e-6
SCIPY_MMNL_FEASIBILITY_EPS = 1e-9
SCIPY_MMNL_FEASIBLE_UPPER_SCALE = 0.95
SCIPY_TEST_EPISODES_DEFAULT = 5

XLOGIT_PRICE_SCALE_DEFAULT = 100.0
XLOGIT_MNL_MAXITER_DEFAULT = 500
XLOGIT_MMNL_DRAWS_DEFAULT = 200
XLOGIT_MMNL_MAXITER_DEFAULT = 300
XLOGIT_VERBOSE = 0

ADP_DEFAULT_MAX_ACTIONS = 4096
ADP_DEFAULT_N_STATE_SAMPLES = 64
ADP_DEFAULT_RIDGE_LAMBDA = 1e-6
ADP_DEFAULT_RANDOM_SEED = 0
ADP_ENV_DEFAULT_N_ROLLOUTS_PER_ACTION = 256
ADP_PROBE_INVENTORY_CAP = 2

RL_TRAIN_N_ENVS = 4
RL_MODEL_VERBOSE = 0
RL_LEARNING_CURVE_FIGSIZE = (8, 5)
RL_LEARNING_CURVE_FILL_ALPHA = 0.2
RL_LEARNING_CURVE_GRID_ALPHA = 0.3
RL_LEARNING_CURVE_DPI = 150

# Experiment-grid constants
GRID_SENSITIVITIES = (False, True)
GRID_TRAIN_ON_ALL_SETS_OPTIONS = (False, True)
GRID_LARGE_PRODUCT_SET_OPTIONS = (False, True)

MULTIBINARY_ALGORITHMS = {
    "A2C",
    "TRPO",
    "PPO"
}

if c.TRAIN_ON_ALL_SETS:
    RL_ALGORITHMS = {
        "A2C": A2C,
        "TRPO": TRPO,
        "PPO": PPO,
    } if c.LARGE_PRODUCT_SET else {
        "DQN": DQN,
        "ARS": ARS,
        "A2C": A2C,
        "TRPO": TRPO,
        "PPO": PPO,
    }
else:
    RL_ALGORITHMS = {
        "DQN": DQN,
        "QRDQN": QRDQN,
        "ARS": ARS,
        "A2C": A2C,
        "TRPO": TRPO,
        "PPO": PPO,
    }


SENSITIVITY_BETA_GT = {
	"low": -0.0015,
	"high": -0.005
}

OUTPUT_DIR = os.path.join(
    BASE_DIR,
    "results",
    f"{'large' if c.LARGE_PRODUCT_SET else 'small'}_{'classical' if c.TRAIN_ON_ALL_SETS else 'model_informed'}_{'high' if c.HIGH_SENSITIVITY else 'low'}_{c.GT_MODEL}",
)
